name: Lint and Format

on:
   push:
   pull_request:
      branches:
         - main

jobs:
   test:
      runs-on: ubuntu-latest
      defaults:
         run:
            working-directory: "frontend"

      steps:
         - uses: actions/checkout@v3
         - uses: actions/setup-node@v3

         - name: Run lint and format
           run: |
              npm install --legacy-peer-deps
              npm run lint
